from pathlib import Path
p=Path('site/js/hehe-business-workbench.js')
s=p.read_text()
def replace_func(name,new):
 global s
 start=s.index('function '+name+'('); end=s.find('\nfunction ',start+10)
 # functions here are adjacent; keep following declaration untouched
 s=s[:start]+new.rstrip()+s[end:]
s=s.replace("diagnostic:{}};","diagnostic:{},serviceSearch:'',recordTab:'drafts',selectedRecord:null};")
s=s.replace("favorites:'我的收藏',guide:","favorites:'资源收藏',services:'服务导航',guide:")
s=s.replace("else if(state.view==='favorites')renderFavorites();else renderWorkspace();","else if(state.view==='favorites')renderFavorites();else if(state.view==='services')renderServices();else renderWorkspace();")
s=s.replace("panel.classList.add('hb-enabled');","panel.classList.add('hb-enabled');panel.dataset.hbView=state.view;")
s=s.replace("b.dataset.nav==='favorites'&&state.view==='favorites'","b.dataset.nav==='favorites'&&state.view==='favorites'||b.dataset.nav==='services'&&state.view==='services'||b.dataset.nav==='new'&&state.view==='home'")
s=s.replace("else if(key==='favorites')navigate('favorites');","else if(key==='favorites')navigate('favorites');else if(key==='services')navigate('services');")
s=s.replace(" render();loadCatalog();"," const nav=panel.querySelector('.hh-side-nav');if(nav&&!nav.querySelector('[data-nav=services]')){const service=B('',()=>navigate('services'),'hh-nav-item');service.dataset.nav='services';service.append(I('apps-2-line'),E('span','','服务导航'));nav.append(service);}const favorite=nav?.querySelector('[data-nav=favorites] span');if(favorite)favorite.textContent='资源收藏';\n render();loadCatalog();")
replace_func('renderHome',r'''function renderHome(){
 const layout=E('div','hb-home-grid');const center=E('div','hb-home-primary');const side=E('aside','hb-home-aside');
 const hero=E('section','hb-hero');const copy=E('div');const title=E('h1','','您好，我是');title.append(E('span','','合合'));copy.append(E('span','hb-eyebrow','数智北京创新中心 · 创新服务工作台'),title,E('p','','帮您了解创新服务、查找资源、准备申请。'));const mascot=E('img');mascot.src=new URL('images/assistant-mascot.png',base).href;mascot.alt='合合';hero.append(copy,mascot);center.append(hero,makeComposer(true));
 const modes=E('div','hb-modes');['问答','问数','边聊边办'].forEach((m,i)=>{const b=B('',()=>{state.mode=m;render();},'hb-mode'+(state.mode===m?' active':''));b.append(I(['message-3-line','bar-chart-box-line','file-edit-line'][i]),E('span','',m));b.setAttribute('aria-pressed',String(state.mode===m));modes.append(b);});center.append(modes);
 const examples=E('div','hb-examples');const ex=state.mode==='问数'?['交通运输领域有哪些政府侧数据目录？','按目录阶段统计场景数量']:state.mode==='边聊边办'?['帮我准备一份需求反馈','我们单位想预约参观创新中心']:['资源申请看不到项目名称，怎么处理？','我们想参与场景创新，应该从哪里开始？'];ex.forEach(q=>examples.append(B(q,()=>send(q),'hb-example')));center.append(examples);
 const cards=E('div','hb-service-cards');[['参与场景揭榜','查找已发布场景，了解申报条件与材料。','了解如何参与','orange','flag-2-line',()=>sceneIntro()],['查找数据资源','查询资源目录，核对获取方式与使用条件。','查找资源','teal','database-2-line',()=>send('交通运输领域有哪些政府侧数据目录？')],['数据创新项目','梳理项目申请与入场准备的办理路径。','准备项目申请','red','file-text-line',()=>send('如何申请公共数据进行数据创新？')],['预约参观','选择个人或团体预约，按页面要求准备信息。','开始预约','blue','calendar-check-line',()=>begin('visit')]].forEach(([title,desc,cta,color,ic,fn])=>{const b=B('',fn,'hb-service '+color);b.append(I(ic),E('h3','',title),E('p','',desc));const go=E('span','hb-service-arrow',cta);go.append(I('arrow-right-line'));b.append(go);cards.append(b);});center.append(cards);
 const strip=E('section','hb-next-strip');strip.append(I('compass-3-line'),E('div','','不知道从哪里开始？按业务目标查看服务'),B('浏览服务导航',()=>navigate('services'),'hb-text-button'));center.append(strip);
 const questions=E('section','hb-surface');questions.append(E('h2','','常见问题'));faq.forEach(q=>{const b=B(q,()=>q.includes('创新场景')?sceneIntro(q):send(q),'hb-list-link');b.append(I('arrow-right-s-line'));questions.append(b);});
 const services=E('section','hb-surface');services.append(E('h2','','常用服务'));[['需求反馈','mail-send-line',()=>begin('demand')],['入驻指南','book-open-line',()=>send('如何申请入驻？')],['加入伙伴','team-line',()=>send('如何加入伙伴？')],['提供资源与能力','stack-line',()=>navigate('services')]].forEach(([label,icon,fn])=>{const b=B('',fn,'hb-service-link');b.append(I(icon),E('span','',label));services.append(b);});side.append(questions,services);layout.append(center,side);body.append(layout);
}''')
# Rich route introduction is a separate consultation state, without forcing a form.
s=s.replace("if(/场景|揭榜|联合体/.test(text)){", "if(/从哪里开始|如何参与场景创新/.test(text)){sceneIntro(text,true);return;}\n if(/场景|揭榜|联合体/.test(text)){")
s=s.replace("if(!m.user)row.append(E('span','hb-avatar','合'));", "if(!m.user){const avatar=E('img','hb-avatar');avatar.src=new URL('images/assistant-mascot.png',base).href;avatar.alt='合合';row.append(avatar);}")
s=s.replace("if(m.source)evidence(content,...m.source);", "if(m.rich==='scene')appendSceneSteps(content);if(m.source)evidence(content,...m.source);")
s=s.replace("head.append(E('strong','','合合助手')", "const avatar=E('img','hb-head-mascot');avatar.src=new URL('images/assistant-mascot.png',base).href;avatar.alt='';head.append(avatar,E('strong','','合合助手')")
s=s.replace("chat.append(chatHost,makeComposer());", "chat.append(chatHost);const suggestions=E('div','hb-chat-suggestions');(state.view==='task'?['需要补充哪些信息？','填写要求是什么？']:state.view==='catalog'?['只看开放的数据','市交通委全部领域']:['能否联合申报？','需要哪些材料？']).forEach(q=>suggestions.append(B(q,()=>send(q),'hb-example')));chat.append(suggestions,makeComposer());")
s=s.replace("const workspace=E('div','hb-workspace'+(split?' split':''));", "const workspace=E('div','hb-workspace'+(split?' split':'')+(['catalog','scenes','guide'].includes(state.view)?' results-view':''));")
# Demand form uses full company row and a clearer source/object summary.
s=s.replace("(f.type==='textarea'?' full':'')", "(f.type==='textarea'||t.kind==='demand'&&f.key==='company'?' full':'')")
s=s.replace("if(f.type==='textarea'){input.rows=4;", "input.placeholder={company:'请输入单位或企业名称',contact:'请输入联系人姓名',phone:'请输入手机号或带区号的固定电话',detail:'请说明应用场景、所需数据范围及希望获得的支持…'}[f.key]||'';if(f.type==='textarea'){input.rows=5;")
s=s.replace("const label=E('label','',f.label+(f.required?' *':''));", "const label=E('label','',f.label);if(f.required)label.append(E('em','hb-required',' *')); ")
s=s.replace("taskHost.append(header);if(t.object)", "taskHost.append(header,E('p','hb-task-description',t.kind==='demand'?'填写您的需求与建议，合合协助整理，提交前由您核对确认。':'按事项要求准备资料，可随时向右侧合合提问。'));if(t.object)")
s=s.replace("t.object.data_name||t.object.scene_name));", "'来源对象：'+(t.object.data_name||t.object.scene_name)));")
# Catalog truth remains unchanged; add a summary and more legible rows.
s=s.replace("const filters=E('div','hb-filterbar');[['domain'", "const metrics=E('div','hb-metrics hb-catalog-metrics');[['政府侧目录',state.catalog.gov.length,'government-line'],['交通运输领域',state.catalog.gov.filter(r=>r.domain_name==='交通运输').length,'bus-line'],['当前筛选结果',catalogRows().length,'file-list-3-line']].forEach(([label,num,icon])=>{const item=E('div');item.append(I(icon),E('span','',label),E('strong','',num.toLocaleString()));metrics.append(item);});taskHost.append(metrics);\n const filters=E('div','hb-filterbar');[['domain'")
s=s.replace("filters.append(search);taskHost.append(filters);", "filters.append(search,B('清除条件',()=>{state.filters={domain:'',dept:'',open:false,keyword:''};state.page=1;renderCatalog();},'hb-text-button'));taskHost.append(filters);")
s=s.replace("const rows=catalogRows();const stat", "const rows=catalogRows();const current=taskHost.querySelector('.hb-catalog-metrics>div:last-child strong');if(current)current.textContent=rows.length.toLocaleString();const stat")
s=s.replace("card.append(title,E('p','hb-muted',r.dept_name", "const icon=I(/轨道/.test(r.data_name)?'subway-line':/公交|客运/.test(r.data_name)?'bus-line':'database-2-line');icon.classList.add('hb-resource-icon');card.append(icon,title,E('p','hb-muted',r.dept_name")
s=s.replace("const actions=E('div','hb-actions');actions.append(B('比较'", "card.append(E('span','hb-tag hb-share-tag','共享标识：'+(r.is_shared||'未提供')));const actions=E('div','hb-actions');actions.append(B(state.compare.includes(r.id)?'已加入比较':'比较'")
# Add source-aware navigation and paired progress panel functions before loadCatalog.
start=s.index('function renderRecords(');end=s.index('function renderFavorites(',start)
s=s[:start]+r'''function ownRows(){return [...state.records.filter(r=>r.owner===state.role),...state.drafts.filter(d=>d.owner===state.role&&d.status!=='模拟已提交'&&!d.recordId).map(d=>({id:d.id,title:d.title,status:'草稿',updated:d.updated,created:d.created,taskId:d.id}))].sort((a,b)=>b.updated-a.updated);}
function resumeRecord(r){const t=state.drafts.find(t=>t.id===r.taskId);if(!t)return;state.task=t;state.thread=state.threads.find(x=>x.id===t.threadId);if(r.status==='待补充'){t.status='草稿';t.confirmation=null;message('继续处理 '+r.id+'，补充后请重新核对，原编号保持不变。');}state.view='task';render();}
function renderRecords(){const head=E('div','hb-page-heading');head.append(E('span','hb-eyebrow','个人服务 / 申请与进度'),E('h1','','我的办理'),E('p','','查看助手草稿、申请记录与当前进展。'));body.append(head);
 if(state.role==='guest'){const empty=E('div','hb-login-empty hb-surface');empty.append(I('shield-user-line'),E('h2','','登录后查看您的办理记录'),E('p','','访客可先准备草稿；本人办理记录需通过认证后按权限读取。'),L('前往官网个人中心 ↗',official.center),B('体验个人用户',()=>changeRole('person')),B('体验企业用户',()=>changeRole('enterprise')));body.append(empty);return;}
 const rows=ownRows();const metrics=E('div','hb-metrics hb-record-metrics');[['助手草稿','草稿','draft-line'],['待补充','待补充','error-warning-line'],['已提交','已提交','file-list-3-line'],['全部记录','全部','folder-open-line']].forEach(([title,filter,icon])=>{const item=B('',()=>{state.recordTab=filter==='草稿'?'drafts':'demo';state.recordFilter=filter;state.selectedRecord=null;render();},'hb-metric-button');item.append(I(icon),E('span','',title),E('strong','',String(rows.filter(r=>filter==='全部'||r.status===filter).length)));metrics.append(item);});body.append(metrics);
 const layout=E('div','hb-record-layout');const list=E('section','hb-record-main');const tabs=E('div','hb-record-tabs');[['drafts','助手草稿'],['demo','模拟办理记录'],['official','正式业务记录']].forEach(([v,label])=>{const b=B(label,()=>{state.recordTab=v;state.recordFilter='全部';state.selectedRecord=null;render();},'hb-filter'+(state.recordTab===v?' active':''));b.setAttribute('aria-pressed',String(state.recordTab===v));tabs.append(b);});list.append(tabs);
 const filters=E('div','hb-record-filters');['全部','草稿','已提交','待补充'].forEach(f=>filters.append(B(f,()=>{state.recordFilter=f;state.recordTab=f==='草稿'?'drafts':f==='全部'?state.recordTab:'demo';state.selectedRecord=null;render();},'hb-filter'+(state.recordFilter===f?' active':''))));const search=E('input');search.placeholder='搜索事项或编号';search.setAttribute('aria-label','搜索我的办理');search.value=state.recordSearch;search.oninput=()=>{state.recordSearch=search.value;renderRecordRows();};filters.append(search);list.append(filters,E('div','hb-record-list'));layout.append(list,E('aside','hb-record-detail'));body.append(layout);renderRecordRows();}
function renderRecordRows(){const host=body.querySelector('.hb-record-list');host.replaceChildren();if(state.recordTab==='official'){host.append(E('div','hb-empty','正式业务记录尚未接入，暂时无法读取您的申请。'),L('前往官网个人中心查询 ↗',official.center));renderRecordPanel(null);return;}
 const list=ownRows().filter(r=>(state.recordTab==='drafts'?r.status==='草稿':r.status!=='草稿')&&(state.recordFilter==='全部'||r.status===state.recordFilter)&&(!state.recordSearch||(r.id+r.title).includes(state.recordSearch)));
 if(!list.length){const empty=E('div','hb-empty');empty.append(I('folder-open-line'),E('h3','','暂无符合条件的记录'),E('p','','从一项真实需求开始，准备的信息会保留在本次访问中。'),B('准备需求反馈',()=>begin('demand')));host.append(empty);}
 const selected=list.find(r=>r.id===state.selectedRecord)||list[0];state.selectedRecord=selected?.id||null;
 list.forEach(r=>{const t=state.drafts.find(d=>d.id===r.taskId);const card=E('article','hb-record'+(selected?.id===r.id?' selected':''));const icon=I(t.kind==='visit'?'calendar-check-line':t.kind==='demand'?'message-3-line':'file-text-line');icon.classList.add('hb-record-icon');const text=E('div','hb-record-copy');text.append(E('h3','',r.title),E('p','',t.object?.data_name||t.object?.scene_name||({demand:'向中心反馈数据需求与服务建议',visit:'准备个人或社会团体参观信息',project:'整理项目目标与资源需求',component:'准备工具信息与单位材料'}[t.kind]||'核对所选场景与申报材料')),E('small','hb-muted',r.id+' · 更新于 '+date(r.updated)));const right=E('div','hb-record-operations');right.append(E('span','hb-tag '+(r.status==='待补充'?'warning':''),r.status+(r.status==='草稿'?' · 未提交':' · 模拟')),B('查看详情',()=>{state.selectedRecord=r.id;renderRecordRows();},'hb-text-button'),B(r.status==='草稿'?'继续准备':r.status==='待补充'?'补充材料':'查看进展',()=>r.status==='已提交'?recordDetail(r):resumeRecord(r),'hb-button secondary'));card.append(icon,text,right);host.append(card);});renderRecordPanel(selected);}
function renderRecordPanel(r){const host=body.querySelector('.hb-record-detail');if(!host)return;host.replaceChildren();host.append(E('h2','','办理进度'));if(!r){host.append(E('p','hb-muted','选择左侧记录，查看准备情况、时间节点与下一步。'));return;}const t=state.drafts.find(d=>d.id===r.taskId);host.append(E('h3','',r.title),E('span','hb-tag',r.status+(r.status==='草稿'?'':' · 模拟')),E('p','hb-muted','创建时间：'+new Date(r.created||t.created).toLocaleString('zh-CN')),E('p','hb-muted','当前身份：'+roleName()));const timeline=E('ol','hb-timeline');timeline.append(E('li','','已创建助手草稿'));const filled=schema(t).filter(f=>t.values[f.key]).length;timeline.append(E('li','',`已填写 ${filled} / ${schema(t).length} 项信息`));t.events.slice(-4).forEach(ev=>timeline.append(E('li','',ev.text)));if(!t.recordId)timeline.append(E('li','pending','待用户核对 · 尚未提交'));host.append(timeline,E('p','hb-notice','助手草稿与正式业务记录分开展示；当前数据仅用于本次演示。'));
 if(r.status==='草稿'||r.status==='待补充')host.append(B(r.status==='草稿'?'继续准备':'补充材料并继续',()=>resumeRecord(r),'hb-button primary'));else{const demo=E('details','hb-evidence');demo.append(E('summary','','演示补正流程'),E('p','','模拟收到补充要求，保留原申请编号。'),B('模拟收到补充要求',()=>{r.status='待补充';r.updated=Date.now();t.events.push({time:Date.now(),text:'需进一步说明资源用途（模拟业务反馈）'});renderRecordRows();}));host.append(demo);}}
function recordDetail(r){state.selectedRecord=r.id;state.recordTab=r.status==='草稿'?'drafts':'demo';state.recordFilter='全部';renderRecordRows();}
''' +s[end:]
insert=r'''
function sceneIntro(text='我们想参与场景创新，应该从哪里开始？',already=false){if(!already)message(text,true);state.task=null;state.view='chat';message('参与场景创新，可以从已发布的城市需求出发，结合自身能力选择机会。建议按以下三步开始：');state.thread.messages.at(-1).rich='scene';state.thread.messages.at(-1).source=['资料来源：公开场景目录与业务操作说明',official.scene,'具体资格、材料和受理时间需按所选场景及批次通知核对。'];render();}
function appendSceneSteps(host){const steps=E('div','hb-answer-steps');[['查看场景目录','浏览已发布场景，了解需求对象与当前目录阶段。',()=>send('查看场景目录')],['核对申报条件','结合所选批次确认参与身份、材料和申请时间。',()=>send('能否以联合体形式进行场景揭榜？')],['准备材料与申请','选定具体场景后准备资料，核对后继续办理。',()=>send('查看场景目录')]].forEach(([title,desc,fn],i)=>{const card=B('',fn,'hb-answer-step');card.append(E('b','',String(i+1)),E('h3','',title),E('p','',desc),I('arrow-right-line'));steps.append(card);});host.append(steps);const actions=E('div','hb-actions');actions.append(B('查看场景目录',()=>send('查看场景目录')),B('查看我的办理',()=>navigate('records'),'hb-button secondary'));host.append(actions);}
function renderServices(){body.append(E('div','hb-page-heading'));const head=body.lastChild;head.append(E('h1','','服务导航'),E('p','','按真实业务分类，快速进入咨询、查询与办理准备。'));const search=E('input','hb-service-search');search.placeholder='搜索服务事项、资源类型、办理指引…';search.setAttribute('aria-label','搜索服务导航');search.value=state.serviceSearch;const grid=E('div','hb-service-directory');body.append(search,grid);
 const groups=[['参与场景创新','发现城市应用需求，参与场景申报。','orange','flag-2-line',[['场景目录',()=>send('查看场景目录')],['场景申请准备',()=>sceneIntro()],['我的申报进度',()=>navigate('records')]]],['开展数据创新','梳理项目、团队与资源使用路径。','red','file-text-line',[['数据创新项目',()=>send('如何申请公共数据进行数据创新？')],['项目 / 团队指引',()=>send('资源申请没有项目名称')],['资源获取指引',()=>send('如何申请公共数据进行数据创新？')]]],['查找创新资源','了解目录内容、获取方式和使用条件。','teal','database-2-line',[['数据目录',()=>send('交通运输领域有哪些政府侧数据目录？')],['云网算力与组件目录',()=>showChat('云网算力、组件和创新成果属于不同资源类别。请从官网数字资源入口选择相应目录，核对资源说明及获取条件。','官网创新服务与资源入口',official.guide,'本原型暂未提供这些类别的完整本地筛选，详情以官网为准。')],['资源收藏',()=>navigate('favorites')]]],['提供资源与能力','准备数据、组件、场景与服务供给信息。','blue','stack-line',[['提供数据',()=>send('提供数据')],['提供组件',()=>begin('component')],['提供场景',()=>send('提供场景')],['提供应用 / 服务',()=>send('提供应用与服务')]]],['到访与服务对接','线下参观、需求反馈与生态合作。','purple','building-line',[['参观预约',()=>begin('visit')],['需求反馈',()=>begin('demand')],['入驻指南',()=>send('如何申请入驻？')],['加入伙伴',()=>send('如何加入伙伴？')]]],['了解评测服务','核对服务方向，反馈验证与评测需求。','cyan','shield-check-line',[['大模型测评',()=>send('大模型测评服务')],['感知算法测评',()=>send('感知算法测评服务')],['技术能力验证',()=>send('技术能力验证评测')]]]];
 const draw=()=>{grid.replaceChildren();const q=state.serviceSearch.trim().replace('场景培育','场景创新').replace('数智创新成果','创新资源');groups.filter(g=>(g[0]+g[1]+g[4].map(x=>x[0]).join('')).includes(q)).forEach(([title,desc,color,icon,links])=>{const card=E('section','hb-directory-card '+color);card.append(I(icon),E('h2','',title),E('p','',desc));links.forEach(([label,fn])=>{const b=B(label,fn,'hb-directory-link');b.append(I('arrow-right-s-line'));card.append(b);});grid.append(card);});if(!grid.children.length)grid.append(E('p','hb-empty','没有匹配服务，请尝试“场景”“组件”或“参观”。'));};search.oninput=()=>{state.serviceSearch=search.value;draw();};draw();}
'''
s=s.replace('async function loadCatalog()',insert+'\nasync function loadCatalog()')
p.write_text(s)
